services:
  robdoe-core-node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: robdoe_sovereign_authority_node
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=${NODE_ENV}
      - IS_DOCKER_CONTAINER=${IS_DOCKER_CONTAINER}
      - WITNESS_PORT=${WITNESS_PORT}
    extra_hosts:
      - "${HOST_GATEWAY_IP}:host-gateway"
    volumes:
      - C:\SPACE:/workspace
      - C:\SPACE\deploy_package\channel_venous_out:/workspace/circulating_data
    ports:
      - "${WITNESS_PORT}:${WITNESS_PORT}"
